services:
  - type: web
    name: portfolio-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: PYTHON_VERSION
        value: 3.11   # or whatever version you used
      - key: SECRET_KEY
        value: your-django-secret-key-here
      - key: DEBUG
        value: False
